name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on pushes to the main branch
  # You can also add a manual trigger with workflow_dispatch
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js (necessary for Eleventy)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # or your preferred Node.js version
    - name: Check if images folder exists
      run: |
        ls -la ./src/assets/images
        ls -la ./src/assets/images/japanImages || echo "Directory not found!"
    - name: Install Tree
      run: sudo apt-get install tree

    - name: View Tree
      run: tree
    # Install dependencies
    - name: Install dependencies
      run: |
        npm install
    - name: Save file structure
      run: |
       tree -a > file-structure.txt
       echo "File structure saved to file-structure.txt"     
    - name: Upload file structure artifact
      uses: actions/upload-artifact@v4
      with:
        name: file-structure
        path: file-structure.txt
    - name: Generate Data to sort images
      run: node ./src/_data/images.js
    # Build the Eleventy site
    - name: Build Eleventy site
      run: |
        npx eleventy  # This will generate the _site directory

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically used for GitHub authentication
        publish_dir: ./_site  # Directory to deploy (your generated site)
